// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY8YtaNNaz9aUpcdPSA5DUBy3rOWDynE8',
    appId: '1:77666331389:web:ab0f87ffb9b41bc400ec94',
    messagingSenderId: '77666331389',
    projectId: 'hijrah-journey',
    authDomain: 'hijrah-journey.firebaseapp.com',
    storageBucket: 'hijrah-journey.appspot.com',
    measurementId: 'G-426EGD3EL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZnVdzW83IGJnWh0c6TPqTML8vDx-RrpU',
    appId: '1:77666331389:android:0f0e16521652321400ec94',
    messagingSenderId: '77666331389',
    projectId: 'hijrah-journey',
    storageBucket: 'hijrah-journey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0m-0Zt_Uz5yA6AmBQm-fGoJyOO58nH6A',
    appId: '1:77666331389:ios:0771c473b8cfddce00ec94',
    messagingSenderId: '77666331389',
    projectId: 'hijrah-journey',
    storageBucket: 'hijrah-journey.appspot.com',
    iosClientId: '77666331389-srtn9p3a6iq41hs5tv8lbcv97al01cqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.hijrahJourney',
  );
}
